### ISSUE TITLE
Appears broken in Bolt 3.1.4

### ISSUE THREAD

**Issue by eduardomart** [jadwigo/TaxonomyList#15]
Error:
`Twig_Error_Syntax
Unknown "taxonomylist" function in "_footer.twig" at line 15.`

**Comment by Raistlfiren** [comment]
@eduardomart Try reinstalling the extension. It seems like the extension isn't being loaded correctly. I just did a fresh install of the latest version of Bolt and the extension, and it seems to be working okay.

**Comment by eduardomart** [comment]
I did try that, same problem.

I briefly talked to @gawainlynch on the Slack channel and he said it's a composer update/install issue and to run this command:

`composer require twig/twig:"<1.26" symfony/twig-bridge:"<2.8.12"`

That seems to have fixed it.

**Comment by Raistlfiren** [comment]
Oh cool, good to hear @eduardomart! :)

**Comment by jadwigo** [comment]
It seems to work out of the box in bolt 3.2.3. So I'm closing this issue here.

If it stops working in later versions please open a new issue.
