### ISSUE TITLE
Passing any options to taxonomylist showing error

### ISSUE THREAD

**Issue by rafpro** [jadwigo/TaxonomyList#16]
both on bolt 3.2.1 and 3.2.3 this extension throwing exception when I am passing any options  such as {'limit': 10, 'weighted': true} but working when only passed ```true```

``` Twig_Error_Runtime in Template.php line 443: 
An exception has been thrown during the rendering of a template ("Notice: Undefined index: options") in "taxonomylist.twig" at line 13.```

**Comment by jadwigo** [comment]
A few questions:

I suppose you are using simeting similar to:
```twig
{% set list = taxonomylist('categories', true) %}
{% for item in list %}
    {{ item.name }}
{% endfor %}
```
What exactly are you doing, someting like? `{% set list = taxonomylist('categories', {'limit': 10, 'weighted': true} ) %}`

What is the taxonomy.yml you are using?

**Comment by jadwigo** [comment]
I tested in on 3.2.3 - and with everything else set to default it seems to be working.

Can you also add the code of `taxonomylist.twig` you are using? Maybe we can see what you have diferently.

**Comment by rafpro** [comment]
Thanks a lot for your reply.

```twig
{% set list = taxonomylist('categories', true) %}
```
Passing only ```true``` is doing everything fine, but when I pass options as second argument to the taxonomylist function, above error is shown. I am going to paste modified version of template of your extension below:
```twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>{{ __('Taxonomies') }}</title>
</head>
<body>
    <h1>{{ __('Hello Twig') }}</h1>
    <h1>{{ __('Taxonomies') }}</h1>
    <ul>
    {% for type in taxonomies %}
        <h3>{{ type }}</h3>
        {% set list = taxonomylist(type, {'limit': 5,'weighted': true}) %}

        {% if list %}
        <ul>
            {% for item in list %}
            <li>
                <a class="taxonomy-{{ item.slug }}" href="{{ item.link }}" title="{{ item.name }}">
                    {{ item.name }}
                    <small>[ {{ item.count }} ]</small>
                </a>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    {% endfor %}

</body>
</html>
```

Mainly I am using your extension heavily in my project to pull information about taxonomies I am using to categorize my content.

I am going to add the screenshot of the error page:
![image](https://cloud.githubusercontent.com/assets/5154612/21102048/89f1e202-c0a6-11e6-8063-39de0ecf4827.png)

Stack trace screenshot:
![image](https://cloud.githubusercontent.com/assets/5154612/21102146/08493b28-c0a7-11e6-805e-0e9dfdb53264.png)

FYKI, it was working fine on Bolt 3.1.4.

**Comment by Raistlfiren** [comment]
The reason you are receiving this is because the latest version of bolt includes error notices when debug is enabled. We will try to have a fix within the next week. Otherwise, PRs are welcome! 😁

**Comment by jadwigo** [comment]
For my quick mockup with Bolt 3.2.3, sqlite, PHP 5.6.29 and Apache 2.2.22 everything seems to work.
On that setup the debug setting does not seem to make a difference. As does `strict_variables: true`

What server and what php version are you running?

**Comment by rafpro** [comment]
Thanks @Raistlfiren for your very helpful trigger :smile: 
@jadwigo :+1: for your nice extension.
