### ISSUE TITLE
Taxonomylist jadwigo insert images

### ISSUE THREAD

**Issue by rotomoco** [jadwigo/TaxonomyList#17]
Hi there!!
I´m using taxonomylist by jadwigo. 
I wish to insert images for each category.
i have a folder with specific .jpgs in public/theme/mytheme/images/*category*.jpg
how can i insert in your code these images with that path?
``` {% set list = taxonomylist('categories', { 'limit': 100, 'weighted': true } ) %}
    <nav class="taggy flex margin center tags icons p-margin">
    {% for item in list %}
<a class="icon fa-tags taxonomy-{{ item.tag }} 
weight-{{ item.weightclass }}" 
href="{{ item.link }}" 
title="{{ item.name }}">
{{ item.name }}
               
        </a>   
    {% endfor %}
    </nav>
``` 

Thank you!!
Roland

**Comment by jadwigo** [comment]
Thanks for making an Issue.

A small page with an example for this is: https://github.com/jadwigo/TaxonomyList/wiki/Tips:-category-images-in-your-listing

**Comment by rotomoco** [comment]
Sorry, but no images are displayed. (
in my twig:
```{% set list = taxonomylist('categories') %}
    <ul>
    {% for item in list %}
        <li>
            <a class="taxonomy-{{ item.slug }}" href="{{ item.link }}" title="{{ item.name }}">
                <img src="custom-base-2016/images/{{ item.slug }}.jpg" alt="{{ item.name }}">
            </a>
        </li>
    {% endfor %}
    </ul>
```
the `{{ path('theme') }}` gives my an themepath-error, so i have changed it to above

my taxonomy.yml:

```categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: { einbauschraenke: "Einbauschränke", einzelmoebel: "Einzelmöbel", regale: "Regale", betten: "Betten", tische: "Tische", gleittueranlagen: "Gleittüranlagen", badmoebel: "Badmöbel", multimedia: "Multimedia", specials: "Specials", retail: "Retail", gastro: "Gastro" }
    listing_template: listing_Kopie.twig
    autocomplete: false
    recordsperpage: 3
    # height: 10em
```

my images are in like: `/custom-base-2016/images/einbauschraenke.jpg`

any suggestions?
Thanks

**Comment by jadwigo** [comment]
If the {{ path('theme') }} does not work you might try {{ paths.theme }} instead, because the path to your image needs to be relative to the root of your server.

**Comment by rotomoco** [comment]
thats fantastic!!
thank you!!
how will i thumb the images now to the good end of this discussion?!?
Great Job!!
