### ISSUE TITLE
Feature request: order by name

### ISSUE THREAD

**Issue by opichon** [jadwigo/TaxonomyList#19]
Currently, if `weighted` option is not set/false, the sortorder defaults to `sortorder ASC`. That my apply to some taxonomies, but for tags, the most likely default sort order is alphabetical, ie by `name ASC`. It would be nice to be able to specify this in the twig function.

**Comment by existentialfrog** [comment]
I second this one. I was just wracking my brain trying to figure out how to make this happen.

**Comment by jadwigo** [comment]
This is added to the extension by #24
