### ISSUE TITLE
Broken in Bolt 3.3 Release

### ISSUE THREAD

**Issue by ajschmidt8** [jadwigo/TaxonomyList#20]
It seems that this line of code breaks the widget in the latest Bolt 3.3 release.
https://github.com/jadwigo/TaxonomyList/blob/master/src/Twig/TaxonomyListExtension.php#L61

See the error message below:
![image](https://user-images.githubusercontent.com/7400326/28747744-fb730eca-745a-11e7-9c0b-016b398fec9e.png)

**Comment by ajschmidt8** [comment]
submitted the following PR:
https://github.com/jadwigo/TaxonomyList/pull/21

**Comment by jadwigo** [comment]
Merged and added as a release
