### ISSUE TITLE
Could not find package jadwigo/taxonomylist at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

### ISSUE THREAD

**Issue by melcarthus** [jadwigo/TaxonomyList#27]
I'm running Bolt 3.5.6.
On my local machine I installed 3.4 which installs perfectly.
On my production machine I installed 3.5, which gives an error:

Could not find package jadwigo/taxonomylist at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability.

**Comment by jadwigo** [comment]
Could you try again - the extension was updated yesterday so the market may have been pointing to a version that was not completely propagated yet.
