### ISSUE TITLE
AJAX: The function "taxonomylist" does not exist in "listing.twig" at line 11

### ISSUE THREAD

**Issue by simnom** [jadwigo/TaxonomyList#8]
Hi,

Bit of a strange issue, calling a page via ajax for instance `/categories/news?page_category_news=2` results in a 500 error and the following error message in the Bolt system log

```
Type: Critical
Context: exception
Route: taxonomylink
URI: /categories/news?page_category_news=2
Details: The function "taxonomylist" does not exist in "listing.twig" at line 11
```

A standard request to the URI works fine :-/

**Comment by jadwigo** [comment]
What is the full url that is requested trought ajax? (you should replace the domain with example.com though)

**Comment by simnom** [comment]
Hi,

The full URL is:

http://example.com/categories/news?page_category_news=2

**Comment by jadwigo** [comment]
What version of bolt do you use? 
(if you are using the latest bleeding edge mastster from git it is probably broken)

Could you post a screenshot of your browser with the full errormessage?

**Comment by jadwigo** [comment]
closing this because there's no reply yet.

feel free to reopen is there's more information
