### ISSUE TITLE
Division by Zero

### ISSUE THREAD

**Issue by psren** [jadwigo/TaxonomyList#9]
If only one item and 1 tag exists, there is a division by zero error.

https://github.com/jadwigo/TaxonomyList/blob/master/Extension.php#L188

Maybe

```php
$difference = $named['maxcount'] - $named['mincount'];
if($difference) {
   $row['weightpercent'] = ($row['count'] - $named['mincount']) / ($named['maxcount'] - $named['mincount']);
} else {
   $row['weightpercent'] = 0;
}
```

**Comment by jadwigo** [comment]
nice catch - never encountered a site with only one item and tag

I'll look into it.
